# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/Home/Documents/SoftProjects/LDM/OAGui/src/Control/Ui/OAControl.ui'
#
# Created: Wed Apr 17 11:07:04 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_OAControl(object):
    def setupUi(self, OAControl):
        OAControl.setObjectName(_fromUtf8("OAControl"))
        OAControl.resize(851, 761)
        OAControl.setMinimumSize(QtCore.QSize(851, 761))
        OAControl.setMaximumSize(QtCore.QSize(851, 761))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/mainIcon")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        OAControl.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(OAControl)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tango_list = QtGui.QTableView(self.centralwidget)
        self.tango_list.setGeometry(QtCore.QRect(30, 190, 791, 271))
        self.tango_list.setObjectName(_fromUtf8("tango_list"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 170, 131, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(35, 20, 51, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.tango_device = QtGui.QLineEdit(self.centralwidget)
        self.tango_device.setGeometry(QtCore.QRect(90, 16, 511, 27))
        self.tango_device.setObjectName(_fromUtf8("tango_device"))
        self.connect_button = QtGui.QPushButton(self.centralwidget)
        self.connect_button.setGeometry(QtCore.QRect(610, 16, 81, 27))
        self.connect_button.setObjectName(_fromUtf8("connect_button"))
        self.tango_status = QtGui.QLabel(self.centralwidget)
        self.tango_status.setGeometry(QtCore.QRect(700, 19, 100, 22))
        self.tango_status.setStyleSheet(_fromUtf8("border: 1px solid black;\n"
"background-color: red;\n"
"color: white"))
        self.tango_status.setAlignment(QtCore.Qt.AlignCenter)
        self.tango_status.setObjectName(_fromUtf8("tango_status"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 70, 791, 91))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.oa_server = QtGui.QLineEdit(self.frame)
        self.oa_server.setGeometry(QtCore.QRect(110, 20, 331, 27))
        self.oa_server.setObjectName(_fromUtf8("oa_server"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(34, 23, 71, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.oa_status = QtGui.QLabel(self.frame)
        self.oa_status.setGeometry(QtCore.QRect(670, 23, 100, 21))
        self.oa_status.setStyleSheet(_fromUtf8("border: 1px solid black;\n"
"background-color: red;\n"
"color: white"))
        self.oa_status.setAlignment(QtCore.Qt.AlignCenter)
        self.oa_status.setObjectName(_fromUtf8("oa_status"))
        self.reload_oa_button = QtGui.QPushButton(self.frame)
        self.reload_oa_button.setGeometry(QtCore.QRect(460, 50, 81, 27))
        self.reload_oa_button.setObjectName(_fromUtf8("reload_oa_button"))
        self.connect_oa_button = QtGui.QPushButton(self.frame)
        self.connect_oa_button.setGeometry(QtCore.QRect(460, 20, 81, 27))
        self.connect_oa_button.setObjectName(_fromUtf8("connect_oa_button"))
        self.oa_queue = QtGui.QLineEdit(self.frame)
        self.oa_queue.setGeometry(QtCore.QRect(380, 50, 61, 27))
        self.oa_queue.setText(_fromUtf8(""))
        self.oa_queue.setReadOnly(True)
        self.oa_queue.setObjectName(_fromUtf8("oa_queue"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(286, 54, 91, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.oa_error = QtGui.QLabel(self.frame)
        self.oa_error.setGeometry(QtCore.QRect(670, 53, 100, 21))
        self.oa_error.setStyleSheet(_fromUtf8("border: 1px solid black;\n"
"background-color: red;\n"
"color: white"))
        self.oa_error.setAlignment(QtCore.Qt.AlignCenter)
        self.oa_error.setObjectName(_fromUtf8("oa_error"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(570, 24, 91, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(570, 53, 91, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 60, 71, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAutoFillBackground(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 470, 501, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.plot_selection = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.plot_selection.setObjectName(_fromUtf8("plot_selection"))
        self.horizontalLayout.addWidget(self.plot_selection)
        self.save_selection = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.save_selection.setObjectName(_fromUtf8("save_selection"))
        self.horizontalLayout.addWidget(self.save_selection)
        self.saveall_button = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.saveall_button.setObjectName(_fromUtf8("saveall_button"))
        self.horizontalLayout.addWidget(self.saveall_button)
        self.clear_button = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.clear_button.setObjectName(_fromUtf8("clear_button"))
        self.horizontalLayout.addWidget(self.clear_button)
        self.exit_button = QtGui.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(710, 477, 113, 27))
        self.exit_button.setObjectName(_fromUtf8("exit_button"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 530, 131, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.error_log = QtGui.QListView(self.centralwidget)
        self.error_log.setGeometry(QtCore.QRect(30, 550, 791, 191))
        self.error_log.setObjectName(_fromUtf8("error_log"))
        OAControl.setCentralWidget(self.centralwidget)
        self.action_exit = QtGui.QAction(OAControl)
        self.action_exit.setObjectName(_fromUtf8("action_exit"))
        self.action_reload = QtGui.QAction(OAControl)
        self.action_reload.setObjectName(_fromUtf8("action_reload"))

        self.retranslateUi(OAControl)
        QtCore.QMetaObject.connectSlotsByName(OAControl)
        OAControl.setTabOrder(self.tango_device, self.connect_button)
        OAControl.setTabOrder(self.connect_button, self.oa_server)
        OAControl.setTabOrder(self.oa_server, self.connect_oa_button)
        OAControl.setTabOrder(self.connect_oa_button, self.oa_queue)
        OAControl.setTabOrder(self.oa_queue, self.reload_oa_button)
        OAControl.setTabOrder(self.reload_oa_button, self.tango_list)
        OAControl.setTabOrder(self.tango_list, self.plot_selection)
        OAControl.setTabOrder(self.plot_selection, self.save_selection)
        OAControl.setTabOrder(self.save_selection, self.saveall_button)
        OAControl.setTabOrder(self.saveall_button, self.clear_button)

    def retranslateUi(self, OAControl):
        OAControl.setWindowTitle(QtGui.QApplication.translate("OAControl", "Online Analysis Control", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("OAControl", "TANGO attributes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("OAControl", "Device", None, QtGui.QApplication.UnicodeUTF8))
        self.tango_device.setText(QtGui.QApplication.translate("OAControl", "ldm/view/dynattr", None, QtGui.QApplication.UnicodeUTF8))
        self.connect_button.setText(QtGui.QApplication.translate("OAControl", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.tango_status.setText(QtGui.QApplication.translate("OAControl", "UNKNOWN", None, QtGui.QApplication.UnicodeUTF8))
        self.oa_server.setText(QtGui.QApplication.translate("OAControl", "ldm/postprocessing/ws", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("OAControl", "OA Server", None, QtGui.QApplication.UnicodeUTF8))
        self.oa_status.setText(QtGui.QApplication.translate("OAControl", "UNKNOWN", None, QtGui.QApplication.UnicodeUTF8))
        self.reload_oa_button.setText(QtGui.QApplication.translate("OAControl", "Reload", None, QtGui.QApplication.UnicodeUTF8))
        self.connect_oa_button.setText(QtGui.QApplication.translate("OAControl", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("OAControl", "Queue length", None, QtGui.QApplication.UnicodeUTF8))
        self.oa_error.setText(QtGui.QApplication.translate("OAControl", "UNKNOWN", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("OAControl", "Proc. status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("OAControl", "Error status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("OAControl", "OA Status", None, QtGui.QApplication.UnicodeUTF8))
        self.plot_selection.setText(QtGui.QApplication.translate("OAControl", "Plot selection", None, QtGui.QApplication.UnicodeUTF8))
        self.save_selection.setText(QtGui.QApplication.translate("OAControl", "Save selection", None, QtGui.QApplication.UnicodeUTF8))
        self.saveall_button.setText(QtGui.QApplication.translate("OAControl", "Save all", None, QtGui.QApplication.UnicodeUTF8))
        self.clear_button.setText(QtGui.QApplication.translate("OAControl", "Reset all", None, QtGui.QApplication.UnicodeUTF8))
        self.exit_button.setText(QtGui.QApplication.translate("OAControl", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("OAControl", "Error log", None, QtGui.QApplication.UnicodeUTF8))
        self.action_exit.setText(QtGui.QApplication.translate("OAControl", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_reload.setText(QtGui.QApplication.translate("OAControl", "Reload configuration", None, QtGui.QApplication.UnicodeUTF8))

import OAControl_rc
