# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/Home/Documents/SoftProjects/LDM/OAGui/src/Editor/Ui/OAEditor.ui'
#
# Created: Wed Apr 17 11:07:05 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_OAEditor(object):
    def setupUi(self, OAEditor):
        OAEditor.setObjectName(_fromUtf8("OAEditor"))
        OAEditor.resize(1231, 941)
        OAEditor.setMinimumSize(QtCore.QSize(1231, 941))
        OAEditor.setMaximumSize(QtCore.QSize(1231, 941))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/mainIcon")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        OAEditor.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(OAEditor)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.main_tab = QtGui.QTabWidget(self.centralwidget)
        self.main_tab.setGeometry(QtCore.QRect(20, 330, 1191, 421))
        self.main_tab.setObjectName(_fromUtf8("main_tab"))
        self.output_tab = QtGui.QWidget()
        self.output_tab.setObjectName(_fromUtf8("output_tab"))
        self.frame = QtGui.QFrame(self.output_tab)
        self.frame.setGeometry(QtCore.QRect(20, 20, 691, 181))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(70, 25, 66, 17))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(70, 65, 66, 17))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(15, 104, 121, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(15, 144, 121, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.oa_module = QtGui.QComboBox(self.frame)
        self.oa_module.setGeometry(QtCore.QRect(140, 20, 521, 27))
        self.oa_module.setEditable(True)
        self.oa_module.setFrame(True)
        self.oa_module.setObjectName(_fromUtf8("oa_module"))
        self.oa_class = QtGui.QComboBox(self.frame)
        self.oa_class.setGeometry(QtCore.QRect(140, 60, 521, 27))
        self.oa_class.setEditable(True)
        self.oa_class.setFrame(True)
        self.oa_class.setObjectName(_fromUtf8("oa_class"))
        self.oa_path_re = QtGui.QComboBox(self.frame)
        self.oa_path_re.setGeometry(QtCore.QRect(140, 100, 521, 27))
        self.oa_path_re.setEditable(True)
        self.oa_path_re.setFrame(True)
        self.oa_path_re.setObjectName(_fromUtf8("oa_path_re"))
        self.oa_outpath = QtGui.QComboBox(self.frame)
        self.oa_outpath.setGeometry(QtCore.QRect(140, 140, 521, 27))
        self.oa_outpath.setEditable(True)
        self.oa_outpath.setFrame(True)
        self.oa_outpath.setObjectName(_fromUtf8("oa_outpath"))
        self.frame_3 = QtGui.QFrame(self.output_tab)
        self.frame_3.setGeometry(QtCore.QRect(20, 230, 691, 141))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.label_5 = QtGui.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(70, 65, 66, 17))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(70, 25, 66, 17))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_9 = QtGui.QLabel(self.frame_3)
        self.label_9.setGeometry(QtCore.QRect(35, 103, 101, 20))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.pres_module = QtGui.QComboBox(self.frame_3)
        self.pres_module.setGeometry(QtCore.QRect(140, 20, 521, 27))
        self.pres_module.setEditable(True)
        self.pres_module.setFrame(True)
        self.pres_module.setObjectName(_fromUtf8("pres_module"))
        self.pres_class = QtGui.QComboBox(self.frame_3)
        self.pres_class.setGeometry(QtCore.QRect(140, 60, 521, 27))
        self.pres_class.setEditable(True)
        self.pres_class.setFrame(True)
        self.pres_class.setObjectName(_fromUtf8("pres_class"))
        self.pres_device = QtGui.QComboBox(self.frame_3)
        self.pres_device.setGeometry(QtCore.QRect(140, 100, 521, 27))
        self.pres_device.setEditable(True)
        self.pres_device.setFrame(True)
        self.pres_device.setObjectName(_fromUtf8("pres_device"))
        self.label_2 = QtGui.QLabel(self.output_tab)
        self.label_2.setGeometry(QtCore.QRect(20, 220, 201, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label = QtGui.QLabel(self.output_tab)
        self.label.setGeometry(QtCore.QRect(20, 10, 161, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.main_tab.addTab(self.output_tab, _fromUtf8(""))
        self.rawdata_tab = QtGui.QWidget()
        self.rawdata_tab.setObjectName(_fromUtf8("rawdata_tab"))
        self.raw_list = QtGui.QTableView(self.rawdata_tab)
        self.raw_list.setGeometry(QtCore.QRect(10, 10, 1041, 371))
        self.raw_list.setCornerButtonEnabled(False)
        self.raw_list.setObjectName(_fromUtf8("raw_list"))
        self.raw_list.verticalHeader().setVisible(False)
        self.raw_add = QtGui.QPushButton(self.rawdata_tab)
        self.raw_add.setGeometry(QtCore.QRect(1070, 10, 98, 27))
        self.raw_add.setObjectName(_fromUtf8("raw_add"))
        self.raw_loadhdf = QtGui.QPushButton(self.rawdata_tab)
        self.raw_loadhdf.setGeometry(QtCore.QRect(1070, 90, 98, 27))
        self.raw_loadhdf.setObjectName(_fromUtf8("raw_loadhdf"))
        self.raw_remove = QtGui.QPushButton(self.rawdata_tab)
        self.raw_remove.setGeometry(QtCore.QRect(1070, 50, 98, 27))
        self.raw_remove.setObjectName(_fromUtf8("raw_remove"))
        self.raw_clear = QtGui.QPushButton(self.rawdata_tab)
        self.raw_clear.setGeometry(QtCore.QRect(1070, 130, 98, 51))
        self.raw_clear.setObjectName(_fromUtf8("raw_clear"))
        self.main_tab.addTab(self.rawdata_tab, _fromUtf8(""))
        self.algo_tab = QtGui.QWidget()
        self.algo_tab.setObjectName(_fromUtf8("algo_tab"))
        self.algo_list = QtGui.QTableView(self.algo_tab)
        self.algo_list.setGeometry(QtCore.QRect(10, 10, 591, 371))
        self.algo_list.setObjectName(_fromUtf8("algo_list"))
        self.algo_moveup = QtGui.QPushButton(self.algo_tab)
        self.algo_moveup.setGeometry(QtCore.QRect(610, 10, 98, 27))
        self.algo_moveup.setObjectName(_fromUtf8("algo_moveup"))
        self.algo_movedown = QtGui.QPushButton(self.algo_tab)
        self.algo_movedown.setGeometry(QtCore.QRect(610, 50, 98, 27))
        self.algo_movedown.setObjectName(_fromUtf8("algo_movedown"))
        self.algo_add = QtGui.QPushButton(self.algo_tab)
        self.algo_add.setGeometry(QtCore.QRect(610, 90, 98, 27))
        self.algo_add.setObjectName(_fromUtf8("algo_add"))
        self.algo_remove = QtGui.QPushButton(self.algo_tab)
        self.algo_remove.setGeometry(QtCore.QRect(610, 130, 98, 27))
        self.algo_remove.setObjectName(_fromUtf8("algo_remove"))
        self.algo_param_list = QtGui.QTableView(self.algo_tab)
        self.algo_param_list.setGeometry(QtCore.QRect(740, 30, 441, 351))
        self.algo_param_list.setObjectName(_fromUtf8("algo_param_list"))
        self.label_17 = QtGui.QLabel(self.algo_tab)
        self.label_17.setGeometry(QtCore.QRect(740, 10, 81, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.algo_duplicate = QtGui.QPushButton(self.algo_tab)
        self.algo_duplicate.setGeometry(QtCore.QRect(610, 170, 98, 27))
        self.algo_duplicate.setObjectName(_fromUtf8("algo_duplicate"))
        self.algo_clear = QtGui.QPushButton(self.algo_tab)
        self.algo_clear.setGeometry(QtCore.QRect(610, 210, 98, 51))
        self.algo_clear.setObjectName(_fromUtf8("algo_clear"))
        self.main_tab.addTab(self.algo_tab, _fromUtf8(""))
        self.pres_tab = QtGui.QWidget()
        self.pres_tab.setObjectName(_fromUtf8("pres_tab"))
        self.pres_list = QtGui.QTableView(self.pres_tab)
        self.pres_list.setGeometry(QtCore.QRect(10, 10, 591, 371))
        self.pres_list.setObjectName(_fromUtf8("pres_list"))
        self.pres_add = QtGui.QPushButton(self.pres_tab)
        self.pres_add.setGeometry(QtCore.QRect(610, 10, 98, 27))
        self.pres_add.setObjectName(_fromUtf8("pres_add"))
        self.pres_remove = QtGui.QPushButton(self.pres_tab)
        self.pres_remove.setGeometry(QtCore.QRect(610, 50, 98, 27))
        self.pres_remove.setObjectName(_fromUtf8("pres_remove"))
        self.label_15 = QtGui.QLabel(self.pres_tab)
        self.label_15.setGeometry(QtCore.QRect(740, 10, 81, 17))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.pres_param_list = QtGui.QTableView(self.pres_tab)
        self.pres_param_list.setGeometry(QtCore.QRect(740, 30, 441, 141))
        self.pres_param_list.setObjectName(_fromUtf8("pres_param_list"))
        self.label_16 = QtGui.QLabel(self.pres_tab)
        self.label_16.setGeometry(QtCore.QRect(740, 180, 81, 17))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.filter_list = QtGui.QTableView(self.pres_tab)
        self.filter_list.setGeometry(QtCore.QRect(740, 200, 441, 141))
        self.filter_list.setObjectName(_fromUtf8("filter_list"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.pres_tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(740, 350, 441, 31))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.filter_add = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.filter_add.setObjectName(_fromUtf8("filter_add"))
        self.horizontalLayout.addWidget(self.filter_add)
        self.filter_remove = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.filter_remove.setObjectName(_fromUtf8("filter_remove"))
        self.horizontalLayout.addWidget(self.filter_remove)
        self.pres_duplicate = QtGui.QPushButton(self.pres_tab)
        self.pres_duplicate.setGeometry(QtCore.QRect(610, 90, 98, 27))
        self.pres_duplicate.setObjectName(_fromUtf8("pres_duplicate"))
        self.pres_clear = QtGui.QPushButton(self.pres_tab)
        self.pres_clear.setGeometry(QtCore.QRect(610, 130, 98, 51))
        self.pres_clear.setObjectName(_fromUtf8("pres_clear"))
        self.main_tab.addTab(self.pres_tab, _fromUtf8(""))
        self.exit = QtGui.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(1060, 900, 151, 27))
        self.exit.setObjectName(_fromUtf8("exit"))
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(20, 40, 951, 81))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.config_file = QtGui.QLineEdit(self.frame_2)
        self.config_file.setGeometry(QtCore.QRect(160, 10, 361, 27))
        self.config_file.setReadOnly(True)
        self.config_file.setObjectName(_fromUtf8("config_file"))
        self.label_10 = QtGui.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(34, 14, 121, 20))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.config_load = QtGui.QPushButton(self.frame_2)
        self.config_load.setGeometry(QtCore.QRect(640, 10, 91, 27))
        self.config_load.setObjectName(_fromUtf8("config_load"))
        self.config_browse = QtGui.QPushButton(self.frame_2)
        self.config_browse.setGeometry(QtCore.QRect(540, 10, 91, 27))
        self.config_browse.setObjectName(_fromUtf8("config_browse"))
        self.config_save = QtGui.QPushButton(self.frame_2)
        self.config_save.setGeometry(QtCore.QRect(740, 10, 91, 27))
        self.config_save.setObjectName(_fromUtf8("config_save"))
        self.config_saveas = QtGui.QPushButton(self.frame_2)
        self.config_saveas.setGeometry(QtCore.QRect(840, 10, 91, 27))
        self.config_saveas.setObjectName(_fromUtf8("config_saveas"))
        self.profile_list = QtGui.QComboBox(self.frame_2)
        self.profile_list.setGeometry(QtCore.QRect(160, 44, 361, 27))
        self.profile_list.setObjectName(_fromUtf8("profile_list"))
        self.label_19 = QtGui.QLabel(self.frame_2)
        self.label_19.setGeometry(QtCore.QRect(4, 46, 151, 20))
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.profile_add = QtGui.QPushButton(self.frame_2)
        self.profile_add.setGeometry(QtCore.QRect(540, 44, 91, 27))
        self.profile_add.setObjectName(_fromUtf8("profile_add"))
        self.profile_delete = QtGui.QPushButton(self.frame_2)
        self.profile_delete.setGeometry(QtCore.QRect(640, 44, 91, 27))
        self.profile_delete.setObjectName(_fromUtf8("profile_delete"))
        self.profile_rename = QtGui.QPushButton(self.frame_2)
        self.profile_rename.setGeometry(QtCore.QRect(740, 44, 91, 27))
        self.profile_rename.setObjectName(_fromUtf8("profile_rename"))
        self.profile_duplicate = QtGui.QPushButton(self.frame_2)
        self.profile_duplicate.setGeometry(QtCore.QRect(840, 44, 91, 27))
        self.profile_duplicate.setObjectName(_fromUtf8("profile_duplicate"))
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(20, 16, 161, 24))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet(_fromUtf8("background-color: gray;\n"
"padding: 4px;\n"
"color: white"))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_20 = QtGui.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(20, 136, 191, 24))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet(_fromUtf8("background-color: gray;\n"
"padding: 4px;\n"
"color: white"))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(20, 160, 951, 141))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.output_browse = QtGui.QPushButton(self.frame_4)
        self.output_browse.setGeometry(QtCore.QRect(620, 10, 121, 27))
        self.output_browse.setObjectName(_fromUtf8("output_browse"))
        self.label_11 = QtGui.QLabel(self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(33, 13, 121, 20))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.output_generate = QtGui.QPushButton(self.frame_4)
        self.output_generate.setGeometry(QtCore.QRect(780, 40, 151, 27))
        self.output_generate.setObjectName(_fromUtf8("output_generate"))
        self.label_13 = QtGui.QLabel(self.frame_4)
        self.label_13.setGeometry(QtCore.QRect(31, 73, 121, 20))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.frame_4)
        self.label_14.setGeometry(QtCore.QRect(11, 103, 141, 20))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_12 = QtGui.QLabel(self.frame_4)
        self.label_12.setGeometry(QtCore.QRect(29, 44, 121, 20))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.output_genreload = QtGui.QPushButton(self.frame_4)
        self.output_genreload.setGeometry(QtCore.QRect(780, 70, 151, 27))
        self.output_genreload.setObjectName(_fromUtf8("output_genreload"))
        self.output_reload = QtGui.QPushButton(self.frame_4)
        self.output_reload.setGeometry(QtCore.QRect(780, 100, 151, 27))
        self.output_reload.setObjectName(_fromUtf8("output_reload"))
        self.tango_browse = QtGui.QPushButton(self.frame_4)
        self.tango_browse.setGeometry(QtCore.QRect(620, 40, 121, 27))
        self.tango_browse.setObjectName(_fromUtf8("tango_browse"))
        self.oa_postprocess = QtGui.QComboBox(self.frame_4)
        self.oa_postprocess.setGeometry(QtCore.QRect(160, 100, 441, 27))
        self.oa_postprocess.setEditable(True)
        self.oa_postprocess.setFrame(True)
        self.oa_postprocess.setObjectName(_fromUtf8("oa_postprocess"))
        self.oa_outputfile = QtGui.QComboBox(self.frame_4)
        self.oa_outputfile.setGeometry(QtCore.QRect(160, 10, 441, 27))
        self.oa_outputfile.setEditable(True)
        self.oa_outputfile.setFrame(True)
        self.oa_outputfile.setObjectName(_fromUtf8("oa_outputfile"))
        self.oa_server = QtGui.QComboBox(self.frame_4)
        self.oa_server.setGeometry(QtCore.QRect(160, 40, 441, 27))
        self.oa_server.setEditable(True)
        self.oa_server.setFrame(True)
        self.oa_server.setObjectName(_fromUtf8("oa_server"))
        self.oa_process = QtGui.QComboBox(self.frame_4)
        self.oa_process.setGeometry(QtCore.QRect(160, 70, 441, 27))
        self.oa_process.setEditable(True)
        self.oa_process.setFrame(True)
        self.oa_process.setObjectName(_fromUtf8("oa_process"))
        self.en_tango = QtGui.QCheckBox(self.frame_4)
        self.en_tango.setGeometry(QtCore.QRect(620, 73, 131, 22))
        self.en_tango.setObjectName(_fromUtf8("en_tango"))
        self.label_21 = QtGui.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(980, 15, 61, 24))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet(_fromUtf8("background-color: gray;\n"
"padding: 4px;\n"
"color: white"))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.log_list = QtGui.QListWidget(self.centralwidget)
        self.log_list.setGeometry(QtCore.QRect(20, 760, 1191, 131))
        self.log_list.setObjectName(_fromUtf8("log_list"))
        self.help_text = QtGui.QTextEdit(self.centralwidget)
        self.help_text.setGeometry(QtCore.QRect(980, 39, 231, 311))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.help_text.sizePolicy().hasHeightForWidth())
        self.help_text.setSizePolicy(sizePolicy)
        self.help_text.setUndoRedoEnabled(False)
        self.help_text.setReadOnly(True)
        self.help_text.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.help_text.setObjectName(_fromUtf8("help_text"))
        self.notification = QtGui.QWidget(self.centralwidget)
        self.notification.setGeometry(QtCore.QRect(840, 309, 31, 31))
        self.notification.setObjectName(_fromUtf8("notification"))
        self.fix_errors = QtGui.QPushButton(self.centralwidget)
        self.fix_errors.setGeometry(QtCore.QRect(882, 312, 81, 27))
        self.fix_errors.setObjectName(_fromUtf8("fix_errors"))
        self.label_22 = QtGui.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(670, 310, 171, 31))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        OAEditor.setCentralWidget(self.centralwidget)
        self.actionExit = QtGui.QAction(OAEditor)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))

        self.retranslateUi(OAEditor)
        self.main_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(OAEditor)
        OAEditor.setTabOrder(self.config_file, self.config_browse)
        OAEditor.setTabOrder(self.config_browse, self.config_load)
        OAEditor.setTabOrder(self.config_load, self.config_save)
        OAEditor.setTabOrder(self.config_save, self.config_saveas)
        OAEditor.setTabOrder(self.config_saveas, self.profile_list)
        OAEditor.setTabOrder(self.profile_list, self.profile_add)
        OAEditor.setTabOrder(self.profile_add, self.profile_delete)
        OAEditor.setTabOrder(self.profile_delete, self.profile_rename)
        OAEditor.setTabOrder(self.profile_rename, self.profile_duplicate)
        OAEditor.setTabOrder(self.profile_duplicate, self.oa_outputfile)
        OAEditor.setTabOrder(self.oa_outputfile, self.output_browse)
        OAEditor.setTabOrder(self.output_browse, self.oa_server)
        OAEditor.setTabOrder(self.oa_server, self.tango_browse)
        OAEditor.setTabOrder(self.tango_browse, self.oa_process)
        OAEditor.setTabOrder(self.oa_process, self.oa_postprocess)
        OAEditor.setTabOrder(self.oa_postprocess, self.output_generate)
        OAEditor.setTabOrder(self.output_generate, self.output_genreload)
        OAEditor.setTabOrder(self.output_genreload, self.output_reload)
        OAEditor.setTabOrder(self.output_reload, self.main_tab)
        OAEditor.setTabOrder(self.main_tab, self.oa_module)
        OAEditor.setTabOrder(self.oa_module, self.oa_class)
        OAEditor.setTabOrder(self.oa_class, self.oa_path_re)
        OAEditor.setTabOrder(self.oa_path_re, self.oa_outpath)
        OAEditor.setTabOrder(self.oa_outpath, self.pres_module)
        OAEditor.setTabOrder(self.pres_module, self.pres_class)
        OAEditor.setTabOrder(self.pres_class, self.pres_device)
        OAEditor.setTabOrder(self.pres_device, self.raw_list)
        OAEditor.setTabOrder(self.raw_list, self.raw_add)
        OAEditor.setTabOrder(self.raw_add, self.raw_remove)
        OAEditor.setTabOrder(self.raw_remove, self.raw_loadhdf)
        OAEditor.setTabOrder(self.raw_loadhdf, self.raw_clear)
        OAEditor.setTabOrder(self.raw_clear, self.algo_list)
        OAEditor.setTabOrder(self.algo_list, self.algo_moveup)
        OAEditor.setTabOrder(self.algo_moveup, self.algo_movedown)
        OAEditor.setTabOrder(self.algo_movedown, self.algo_add)
        OAEditor.setTabOrder(self.algo_add, self.algo_remove)
        OAEditor.setTabOrder(self.algo_remove, self.algo_duplicate)
        OAEditor.setTabOrder(self.algo_duplicate, self.algo_clear)
        OAEditor.setTabOrder(self.algo_clear, self.algo_param_list)
        OAEditor.setTabOrder(self.algo_param_list, self.pres_list)
        OAEditor.setTabOrder(self.pres_list, self.pres_add)
        OAEditor.setTabOrder(self.pres_add, self.pres_remove)
        OAEditor.setTabOrder(self.pres_remove, self.pres_duplicate)
        OAEditor.setTabOrder(self.pres_duplicate, self.pres_clear)
        OAEditor.setTabOrder(self.pres_clear, self.pres_param_list)
        OAEditor.setTabOrder(self.pres_param_list, self.filter_list)
        OAEditor.setTabOrder(self.filter_list, self.filter_add)
        OAEditor.setTabOrder(self.filter_add, self.filter_remove)
        OAEditor.setTabOrder(self.filter_remove, self.help_text)
        OAEditor.setTabOrder(self.help_text, self.log_list)
        OAEditor.setTabOrder(self.log_list, self.exit)

    def retranslateUi(self, OAEditor):
        OAEditor.setWindowTitle(QtGui.QApplication.translate("OAEditor", "Online Analysis Configuration Editor", None, QtGui.QApplication.UnicodeUTF8))
        OAEditor.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Specifies the full path of the file that will be loaded by the OnlineAnalysis server. </p><p><span style=\"font-weight:600;\">WARNING: change it only if you know what you are doing. A wrong path will prevent the OA to load the new configuration file.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.main_tab.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Each tab is devoted to the configuration of a part of the OnlineAnalysis server. The <span style=\" font-weight:600;\">&quot;Output&quot;</span> tab is used to configure the output server. The <span style=\" font-weight:600;\">&quot;Raw data&quot;</span> tab is used to configure which dataset are loaded from the HDF5 files. The <span style=\" font-weight:600;\">&quot;Algorithms&quot;</span> tab configure the processing part. The <span style=\" font-weight:600;\">&quot;Presentation&quot;</span> part configures the post-processing part (i.e. data accumulation).</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("OAEditor", "Module", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("OAEditor", "Class", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("OAEditor", "Original path RE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("OAEditor", "Substitution path", None, QtGui.QApplication.UnicodeUTF8))
        self.oa_module.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>The module from which the OnlineAnalysis server should load the processing output class. </p><p><span style=\" font-weight:600;\">WARNING: a wrong value here may prevent the OA from working. Change it only if you know what you are doing.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.oa_class.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>The Python class that will handle the output of the processing part, i.e. the results from the algorithms. The standard output modules are:\n"
"<ul>\n"
"<li><b>NoOut:</b> this module will do nothing</li>\n"
"<li><b>OA2HDF:</b> this module will save the results in an HDF5 file (one file for each input file, with results saved bunch by bunch).</li>\n"
"</ul>\n"
"</p><p><span style=\" font-weight:600;\">WARNING: a wrong value here may prevent the OA from working. Change it only if you know what you are doing.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.oa_path_re.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>A regular expression used by the OA2HDF output module to mangle the path of the file loaded by the OA to produce the path in which the ouput file should be saved.</p><p><span style=\" font-weight:600;\">WARNING: a wrong value here will prevent the OA2HDF module from saving files or may save files in unexpected locations. Change it with care.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.oa_outpath.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>The value used by the OA2HDF module as a replacement for the path selected by the regular expression to produce the output path.</p><p><span style=\" font-weight:600;\">WARNING: a wrong value here will prevent the OA2HDF module from saving files or may save files in unexpected locations. Change it with care.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("OAEditor", "Class", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("OAEditor", "Module", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("OAEditor", "TANGO device", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_module.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>The module from which the OnlineAnalysis server should load the presentation output class. </p><p><span style=\" font-weight:600;\">WARNING: a wrong value here may prevent the OA from working. Change it only if you know what you are doing.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_class.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The Python class that will handle the output of the post-processing part, i.e. the results from the presenters. The standard output modules are:\n"
"<ul>\n"
"<li><b>NoOut:</b> this module will do nothing</li>\n"
"<li><b>Export2Tango:</b> this module will output the results to a DynamicAttribute TANGO server.</li>\n"
"</ul>\n"
"</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">WARNING: a wrong value here may prevent the OA from working. Change it only if you know what you are doing.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_device.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>The path to the DynamicAttribute TANGO device that will handle the distribution of the results. If the device is not configured in the standard TANGO database for the machine hosting the OA server, the full address of the DB server must be specified (e.g. dbserver.elettra.trieste.unimi.it:10000/path/to/dynserver)</p><p><span style=\" font-weight:600;\">WARNING: a wrong value here will prevent the Export2Tango module to operate. Change it with care.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("OAEditor", "Online analysis presentation", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("OAEditor", "Online analysis output", None, QtGui.QApplication.UnicodeUTF8))
        self.main_tab.setTabText(self.main_tab.indexOf(self.output_tab), QtGui.QApplication.translate("OAEditor", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.raw_list.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>List of all the raw datasets configured in the current profile. Only those with the enable tick will be included in the output file.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.raw_add.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Add a new dataset definition.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.raw_add.setText(QtGui.QApplication.translate("OAEditor", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.raw_loadhdf.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Generate dataset definitions starting from an HDF5 file. The file should be available locally on the PC running the editor. After the file is loaded a window is presented to review the datasets. The selected ones may be both appended to the current configuration or may replace it completely.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.raw_loadhdf.setText(QtGui.QApplication.translate("OAEditor", "Load HDF5", None, QtGui.QApplication.UnicodeUTF8))
        self.raw_remove.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Remove the currently selected element.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.raw_remove.setText(QtGui.QApplication.translate("OAEditor", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.raw_clear.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Duplicate the currently selected algorithm. The new algorithm will be appended at the end of the processing pipeline and it\'s output variables will be cleared.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.raw_clear.setText(QtGui.QApplication.translate("OAEditor", "Clear\n"
"disabled", None, QtGui.QApplication.UnicodeUTF8))
        self.main_tab.setTabText(self.main_tab.indexOf(self.rawdata_tab), QtGui.QApplication.translate("OAEditor", "Raw data", None, QtGui.QApplication.UnicodeUTF8))
        self.algo_list.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>List of all the algorithms configured in the current profile. Only those with the enable tick will be included in the output file. The algorithms will be executed in the order in which they are displayed.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.algo_moveup.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Move the selected algorithm earlier in the processing pipeline.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.algo_moveup.setText(QtGui.QApplication.translate("OAEditor", "Move Up", None, QtGui.QApplication.UnicodeUTF8))
        self.algo_movedown.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Move the selected algorithm later in the processing pipeline.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.algo_movedown.setText(QtGui.QApplication.translate("OAEditor", "Move Down", None, QtGui.QApplication.UnicodeUTF8))
        self.algo_add.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Add a new algorithm. The new algorithm will be appended at the end of the processing pipeline.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.algo_add.setText(QtGui.QApplication.translate("OAEditor", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.algo_remove.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Remove the currenly selected algorithm.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.algo_remove.setText(QtGui.QApplication.translate("OAEditor", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.algo_param_list.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>The parameter list of the currently selected algorithm.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("OAEditor", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.algo_duplicate.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Duplicate the currently selected algorithm. The new algorithm will be appended at the end of the processing pipeline and it\'s output variables will be cleared.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.algo_duplicate.setText(QtGui.QApplication.translate("OAEditor", "Duplicate", None, QtGui.QApplication.UnicodeUTF8))
        self.algo_clear.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Duplicate the currently selected algorithm. The new algorithm will be appended at the end of the processing pipeline and it\'s output variables will be cleared.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.algo_clear.setText(QtGui.QApplication.translate("OAEditor", "Clear\n"
"disabled", None, QtGui.QApplication.UnicodeUTF8))
        self.main_tab.setTabText(self.main_tab.indexOf(self.algo_tab), QtGui.QApplication.translate("OAEditor", "Algorithms", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_list.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>List of all the presenters configured in the current profile. Only those with the enable tick will be included in the output file.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_add.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Add a new presenter.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_add.setText(QtGui.QApplication.translate("OAEditor", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_remove.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Remove the currently selected presenter.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_remove.setText(QtGui.QApplication.translate("OAEditor", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("OAEditor", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_param_list.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Parameter list of the currently selected presenter.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("OAEditor", "Filters", None, QtGui.QApplication.UnicodeUTF8))
        self.filter_list.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>The filter list of the currently selected presenter.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.filter_add.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Add a new filter to the current presenter.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.filter_add.setText(QtGui.QApplication.translate("OAEditor", "Add filter", None, QtGui.QApplication.UnicodeUTF8))
        self.filter_remove.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Remove the currently selected filter.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.filter_remove.setText(QtGui.QApplication.translate("OAEditor", "Remove filter", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_duplicate.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Duplicate the currently selected presenter. The output variables of the new presenter will be cleared.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_duplicate.setText(QtGui.QApplication.translate("OAEditor", "Duplicate", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_clear.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Duplicate the currently selected algorithm. The new algorithm will be appended at the end of the processing pipeline and it\'s output variables will be cleared.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pres_clear.setText(QtGui.QApplication.translate("OAEditor", "Clear\n"
"disabled", None, QtGui.QApplication.UnicodeUTF8))
        self.main_tab.setTabText(self.main_tab.indexOf(self.pres_tab), QtGui.QApplication.translate("OAEditor", "Presentation", None, QtGui.QApplication.UnicodeUTF8))
        self.exit.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Close the configuration editor.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.exit.setText(QtGui.QApplication.translate("OAEditor", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.config_file.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>The path to the configuration file for the editor.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.config_file.setText(QtGui.QApplication.translate("OAEditor", "/home/ldm/OAConfig/oa_editor_config.xml", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("OAEditor", "Configuration file", None, QtGui.QApplication.UnicodeUTF8))
        self.config_load.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Load the specified configuration file.</p><p><span style=\" font-weight:600;\">NOTE: reloading will discard all the unsaved modifications to all profiles.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.config_load.setText(QtGui.QApplication.translate("OAEditor", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.config_browse.setToolTip(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Pippo!</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.config_browse.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Open a file browser to search for the editor\'s configuration file.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.config_browse.setText(QtGui.QApplication.translate("OAEditor", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.config_save.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Save all the modifications to the configuration file. Note that all profiles will be saved, not only the current one.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.config_save.setText(QtGui.QApplication.translate("OAEditor", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.config_saveas.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Save a backup copy of the configuration file to a different location.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.config_saveas.setText(QtGui.QApplication.translate("OAEditor", "Save as...", None, QtGui.QApplication.UnicodeUTF8))
        self.profile_list.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Select the current configuration profile. Changing profile will not affect modifications made to other profiles.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("OAEditor", "Configuration profile", None, QtGui.QApplication.UnicodeUTF8))
        self.profile_add.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Add a new empty profile to the configuration.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.profile_add.setText(QtGui.QApplication.translate("OAEditor", "Add new", None, QtGui.QApplication.UnicodeUTF8))
        self.profile_delete.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Delete the currently selected profile.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.profile_delete.setText(QtGui.QApplication.translate("OAEditor", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.profile_rename.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Rename the currently selected profile.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.profile_rename.setText(QtGui.QApplication.translate("OAEditor", "Rename", None, QtGui.QApplication.UnicodeUTF8))
        self.profile_duplicate.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Duplicate the current profile.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.profile_duplicate.setText(QtGui.QApplication.translate("OAEditor", "Duplicate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("OAEditor", "Input configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("OAEditor", "OA server configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.output_browse.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Open a file browser to select the location of the output configuration file.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.output_browse.setText(QtGui.QApplication.translate("OAEditor", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("OAEditor", "Output file", None, QtGui.QApplication.UnicodeUTF8))
        self.output_generate.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Generate a new configuration file for the Online Analysis server. The new file will not be used until a reload command will be issued to the OA server.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.output_generate.setText(QtGui.QApplication.translate("OAEditor", "Generate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("OAEditor", "OA processing", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("OAEditor", "OA post-processing", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("OAEditor", "OA Server", None, QtGui.QApplication.UnicodeUTF8))
        self.output_genreload.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Generate a new configuration file for the Online Analysis server and issue a reload command.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.output_genreload.setText(QtGui.QApplication.translate("OAEditor", "Generate && Reload", None, QtGui.QApplication.UnicodeUTF8))
        self.output_reload.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Issue a reload command to the Online Analysis server. Without a new configuration file, this is equivalent to a complete reset of the OA output.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.output_reload.setText(QtGui.QApplication.translate("OAEditor", "Reload", None, QtGui.QApplication.UnicodeUTF8))
        self.tango_browse.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Browse the TANGO database to select the OA server. Works only if the environment variable TANGO_HOST is set.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tango_browse.setText(QtGui.QApplication.translate("OAEditor", "Browse TANGO", None, QtGui.QApplication.UnicodeUTF8))
        self.oa_postprocess.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>The post-processing module and function loaded by the WorkSpawner server.</p><p><span style=\" font-weight:600;\">WARNING: change it only if you know what you are doing. A wrong value will prevent the OA to operate.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.oa_outputfile.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Specifies the full path of the file that will be loaded by the OnlineAnalysis server. </p><p><span style=\"font-weight:600;\">WARNING: change it only if you know what you are doing. A wrong path will prevent the OA to load the new configuration file.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.oa_server.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>TANGO device of the Online Analysisi server.</p><p><span style=\"font-weight:600;\">WARNING: change it only if you know what you are doing. A wrong value will prevent the OA to operate.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.oa_process.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>The processing module and function loaded by the WorkSpawner server.</p><p><span style=\"font-weight:600;\">WARNING: change it only if you know what you are doing. A wrong value will prevent the OA to operate.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.en_tango.setText(QtGui.QApplication.translate("OAEditor", "Enable TANGO", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("OAEditor", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.log_list.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>This box will show all the logging events from the editor applications. Useful to debug problems that are not clearly presented by error popups. When asking for help, look here to find latest errors occured.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.help_text.setHtml(QtGui.QApplication.translate("OAEditor", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Online help. Move the cursor over a control to see a brief description.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.fix_errors.setWhatsThis(QtGui.QApplication.translate("OAEditor", "<html><head/><body><p>Open a file browser to select the location of the output configuration file.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.fix_errors.setText(QtGui.QApplication.translate("OAEditor", "Fix errors", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("OAEditor", "Configuration integrity:", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("OAEditor", "Exit", None, QtGui.QApplication.UnicodeUTF8))

import OAEditor_rc
